In [97]:
import os
import pandas as pd
extract_path = r"C:\Users\xyz\Desktop\bodi2"

ohlcv_data_new = pd.read_csv(os.path.join(extract_path, "1h_ETH_withFeatures_v2.csv"))
ohlcv_data_new

,Unnamed: 0.1,Unnamed: 0,Open_time,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,...,Feature_384_19,Feature_384_20,Feature_384_21,Feature_384_22,Feature_384_23,Feature_384_24,Feature_384_25,Feature_384_26,Feature_384_27,Feature_384_28
0,0,0,2020-01-01 00:00:00,129.16,129.19,128.68,128.87,7769.17336,1577840399999,1.000930e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,2020-01-01 01:00:00,128.87,130.65,128.78,130.64,11344.65516,1577843999999,1.474278e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2,2020-01-01 02:00:00,130.63,130.98,130.35,130.85,7603.35623,1577847599999,9.940256e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,3,2020-01-01 03:00:00,130.85,130.89,129.94,130.20,4968.55433,1577851199999,6.473610e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,4,2020-01-01 04:00:00,130.21,130.74,130.15,130.20,3397.90747,1577854799999,4.430067e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30636,30636,30640,2023-08-11 18:59:42.720,1843.95,1844.61,1841.64,1843.97,24912.98300,1691783999999,4.592308e+07,...,38811.215000,38811.215000,0.424857,-0.027205,0.430342,-0.021281,0.452062,0.0,0.457547,0.005924
30637,30637,30641,2023-08-11 20:00:52.736,1843.98,1845.10,1843.22,1845.09,18963.40500,1691787599999,3.497073e+07,...,34178.471000,34178.471000,0.424528,-0.027534,0.430013,-0.021610,0.452062,0.0,0.457547,0.005924
30638,30638,30642,2023-08-11 20:59:51.680,1845.10,1845.84,1843.00,1844.83,14427.80700,1691791199999,2.661282e+07,...,30374.704500,30374.704500,0.412242,-0.039820,0.417727,-0.033896,0.452062,0.0,0.457547,0.005924
30639,30639,30643,2023-08-11 22:01:01.696,1844.82,1846.67,1844.27,1845.72,12951.20900,1691794799999,2.390141e+07,...,27185.325000,27185.325000,0.415094,-0.036968,0.420579,-0.031044,0.452062,0.0,0.457547,0.005924
30640,30640,30644,2023-08-11 23:00:00.640,1845.73,1851.58,1845.31,1848.04,38004.13200,1691798399999,7.024763e+07,...,24812.972333,24812.972333,0.409010,-0.047155,0.414545,-0.041178,0.456166,0.0,0.461700,0.005977

In [98]:

# Function to calculate the True Range
def true_range(high, low, prev_close):
    return max(high - low, abs(high - prev_close), abs(low - prev_close))

# Calculating the True Range for each row
ohlcv_data_new['true_range'] = ohlcv_data_new.apply(lambda row: true_range(row['High'], row['Low'], ohlcv_data_new.loc[row.name - 1, 'Close'] if row.name > 0 else 0), axis=1)

# Calculating the Average True Range (ATR) using a rolling window of 14 periods
atr_period = 14
ohlcv_data_new['atr'] = ohlcv_data_new['true_range'].rolling(window=atr_period).mean()

# Displaying the first few rows with the true range and ATR
ohlcv_data_new.head(20)

,Unnamed: 0.1,Unnamed: 0,Open_time,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,...,Feature_384_21,Feature_384_22,Feature_384_23,Feature_384_24,Feature_384_25,Feature_384_26,Feature_384_27,Feature_384_28,true_range,atr
0,0,0,2020-01-01 00:00:00,129.16,129.19,128.68,128.87,7769.17336,1577840399999,1.000930e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,129.19,NaN
1,1,1,2020-01-01 01:00:00,128.87,130.65,128.78,130.64,11344.65516,1577843999999,1.474278e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.87,NaN
2,2,2,2020-01-01 02:00:00,130.63,130.98,130.35,130.85,7603.35623,1577847599999,9.940256e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.63,NaN
3,3,3,2020-01-01 03:00:00,130.85,130.89,129.94,130.20,4968.55433,1577851199999,6.473610e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.95,NaN
4,4,4,2020-01-01 04:00:00,130.21,130.74,130.15,130.20,3397.90747,1577854799999,4.430067e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.59,NaN
5,5,5,2020-01-01 05:00:00,130.20,130.47,130.11,130.30,4243.60640,1577858399999,5.529727e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.36,NaN
6,6,6,2020-01-01 06:00:00,130.31,130.75,130.26,130.44,3668.90166,1577861999999,4.789442e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49,NaN
7,7,7,2020-01-01 07:00:00,130.47,130.71,130.14,130.24,4147.17413,1577865599999,5.407707e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.57,NaN
8,8,8,2020-01-01 08:00:00,130.24,130.41,129.87,130.36,7541.44497,1577869199999,9.808940e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.54,NaN
9,9,9,2020-01-01 09:00:00,130.40,130.62,130.13,130.17,4808.20496,1577872799999,6.268190e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49,NaN
10,10,10,2020-01-01 10:00:00,130.17,130.82,130.07,130.70,4625.50170,1577876399999,6.035756e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.75,NaN
11,11,11,2020-01-01 11:00:00,130.67,131.87,130.60,130.74,10847.79032,1577879999999,1.424063e+06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.27,NaN
12,12,12,2020-01-01 12:00:00,130.74,131.61,130.70,131.61,4163.30667,1577883599999,5.460708e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.91,NaN
13,13,13,2020-01-01 13:00:00,131.60,131.90,131.28,131.68,7160.65302,1577887199999,9.423669e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.62,9.945000
14,14,14,2020-01-01 14:00:00,131.66,132.37,131.24,131.96,7325.25762,1577890799999,9.662354e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.13,0.797857
15,15,15,2020-01-01 15:00:00,131.95,132.40,131.60,132.08,5361.06926,1577894399999,7.073830e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.80,0.721429
16,16,16,2020-01-01 16:00:00,132.08,132.95,131.78,132.85,6915.20906,1577897999999,9.146434e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.17,0.760000
17,17,17,2020-01-01 17:00:00,132.86,133.05,132.27,132.34,5424.00732,1577901599999,7.193977e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.78,0.747857
18,18,18,2020-01-01 18:00:00,132.34,132.46,131.57,132.04,5707.79340,1577905199999,7.532437e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,0.769286
19,19,19,2020-01-01 19:00:00,132.04,132.16,131.62,131.86,2111.21443,1577908799999,2.783557e+05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.54,0.782143

In [99]:
# Function to label a data point based on the given condition

atr_plus = 2
atr_minus = 1

def label_data(row):
    current_close = row['Close']
    current_atr = row['atr']
    future_closes = ohlcv_data_new.loc[row.name + 1:, 'Close'].values

    # Check for the condition: Close price rises by 2 ATR before falling by 1 ATR
    has_risen_2_atr = False
    for future_close in future_closes:
        price_diff = future_close - current_close
        if price_diff <= -atr_minus*current_atr:
            return False
        if price_diff >= atr_plus * current_atr:
            return True

# Apply the labeling function to each row
ohlcv_data_new['label'] = ohlcv_data_new.apply(label_data, axis=1)

# Displaying the first few rows with the label

In [94]:
ohlcv_data_new.label.describe()

count     30604
unique        2
top       False
freq      17400
Name: label, dtype: object

In [95]:
import numpy as np

np.count_nonzero(ohlcv_data_new.label == False), np.count_nonzero(ohlcv_data_new.label == True)

(17400, 13204)

In [100]:
ohlcv_data_new.to_csv(os.path.join(extract_path, "eth1h_withlabel_andfeatures_v2.csv"))

In [79]:
ohlcv_data_new

,Unnamed: 0.1,Unnamed: 0,Open_time,Open,High,Low,Close,Volume,Close_time,Quote_asset_volume,...,Feature_336_22,Feature_336_23,Feature_336_24,Feature_336_25,Feature_336_26,Feature_336_27,Feature_336_28,true_range,atr,label
0,0,0,2021-12-01 00:00:00,4630.25,4731.40,4598.77,4723.92,41743.3235,1638320399999,1.954175e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4731.40,NaN,None
1,1,1,2021-12-01 01:00:00,4723.91,4723.92,4680.24,4690.57,18184.0592,1638323999999,8.546848e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.68,NaN,None
2,2,2,2021-12-01 02:00:00,4690.56,4750.00,4665.20,4748.91,22668.9820,1638327599999,1.067585e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.80,NaN,None
3,3,3,2021-12-01 03:00:00,4748.92,4769.07,4716.54,4759.37,27490.5019,1638331199999,1.304372e+08,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52.53,NaN,None
4,4,4,2021-12-01 04:00:00,4759.37,4762.73,4712.22,4726.85,18072.6271,1638334799999,8.559542e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.51,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13866,13866,13870,2023-08-11 18:59:42.720,1843.95,1844.61,1841.64,1843.97,24912.9830,1691783999999,4.592308e+07,...,0.493382,0.494138,-0.024833,0.0,0.525022,0.525778,0.006807,2.97,4.942857,None
13867,13867,13871,2023-08-11 20:00:52.736,1843.98,1845.10,1843.22,1845.09,18963.4050,1691787599999,3.497073e+07,...,0.479264,0.480020,-0.038951,0.0,0.525022,0.525778,0.006807,1.88,4.891429,None
13868,13868,13872,2023-08-11 20:59:51.680,1845.10,1845.84,1843.00,1844.83,14427.8070,1691791199999,2.661282e+07,...,0.482541,0.483298,-0.035674,0.0,0.525022,0.525778,0.006807,2.84,4.946429,None
13869,13869,13873,2023-08-11 22:01:01.696,1844.82,1846.67,1844.27,1845.72,12951.2090,1691794799999,2.390141e+07,...,0.471322,0.472079,-0.046893,0.0,0.525022,0.525778,0.006807,2.40,4.890714,None
13870,13870,13874,2023-08-11 23:00:00.640,1845.73,1851.58,1845.31,1848.04,38004.1320,1691798399999,7.024763e+07,...,0.442077,0.442834,-0.076138,0.0,0.525022,0.525778,0.006807,6.27,5.171429,None

In [82]:
(ohlcv_data_new.atr/ohlcv_data_new.Close).describe()

count    13858.000000
mean         0.010315
std          0.006281
min          0.001447
25%          0.006296
50%          0.009112
75%          0.012570
max          0.084371
dtype: float64

In [32]:
m = (ohlcv_data_new[[c for c in ohlcv_data_new if "landmark" in c]] > 0).astype(int).sum(axis=1)>2
import numpy as np
np.count_nonzero(m)

960

In [33]:
np.count_nonzero(ohlcv_data_new.loc[m].label2), np.count_nonzero(ohlcv_data_new.loc[~m].label2), np.count_nonzero(~ohlcv_data_new.loc[m].label2), np.count_nonzero(~ohlcv_data_new.loc[~m].label2)

(166, 148, 794, 1100)